CREATE TABLE loan_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255),
    mode VARCHAR(255),
    status VARCHAR(255),
    requested_amount NUMERIC(38, 2),
    tenure_months INTEGER,
    created_at TIMESTAMP(6),
    user_id BIGINT,
    CONSTRAINT fk_loan_applications_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
);
