CREATE TABLE financial_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL UNIQUE,
    employment_type VARCHAR(255),
    monthly_income NUMERIC(38, 2),
    monthly_expenses NUMERIC(38, 2),
    existing_debt_payment NUMERIC(38, 2),
    repayment_history VARCHAR(255),
    income_stability VARCHAR(255),
    CONSTRAINT fk_financial_profiles_application
        FOREIGN KEY (application_id)
        REFERENCES loan_applications (id)
);
