CREATE TABLE credit_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL UNIQUE,
    score INTEGER,
    risk_level VARCHAR(255),
    dti_ratio NUMERIC(38, 2),
    expense_ratio NUMERIC(38, 2),
    repayment_capacity NUMERIC(38, 2),
    suggested_loan_limit NUMERIC(38, 2),
    positive_factors VARCHAR(1000),
    risk_factors VARCHAR(1000),
    created_at TIMESTAMP(6),
    CONSTRAINT fk_credit_scores_application
        FOREIGN KEY (application_id)
        REFERENCES loan_applications (id)
);
