CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    document_type VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    stored_file_path VARCHAR(1000) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_documents_application
        FOREIGN KEY (application_id)
        REFERENCES loan_applications (id)
);

CREATE INDEX idx_documents_application_id ON documents (application_id);
