CREATE TABLE extracted_financial_fields (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL UNIQUE,
    extracted_text VARCHAR(4000),
    monthly_income NUMERIC(38, 2),
    monthly_expenses NUMERIC(38, 2),
    existing_debt_payment NUMERIC(38, 2),
    confidence_score NUMERIC(38, 2),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_extracted_financial_fields_document
        FOREIGN KEY (document_id)
        REFERENCES documents (id)
);
