CREATE TABLE consent_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    purpose VARCHAR(255) NOT NULL,
    accepted BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_consent_records_application
        FOREIGN KEY (application_id)
        REFERENCES loan_applications (id),
    CONSTRAINT fk_consent_records_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
);

CREATE INDEX idx_consent_records_application_id ON consent_records (application_id);

CREATE TABLE audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    application_id BIGINT,
    action VARCHAR(255) NOT NULL,
    details VARCHAR(1000),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_audit_events_user
        FOREIGN KEY (user_id)
        REFERENCES users (id),
    CONSTRAINT fk_audit_events_application
        FOREIGN KEY (application_id)
        REFERENCES loan_applications (id)
);

CREATE INDEX idx_audit_events_application_id ON audit_events (application_id);
CREATE INDEX idx_audit_events_user_id ON audit_events (user_id);
